<html>

<head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <link rel="stylesheet" type="text/css" href="/lessons/styles.css">
</head>

<body class="c14 doc-content">
    <h1 class="c0 c19">Tratarea erorilor. </h1>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c16">Construc&#539;ia try..catch..finally.</span></p>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c1">&Icirc;n timpul execu&#539;iei programului, pot ap&#259;rea diferite erori care
            perturb&#259; fluxul normal al programului &#537;i, uneori, determin&#259; &icirc;ntreruperea execu&#539;iei
            acestuia. Limbajul JavaScript dispune de instrumente pentru gestionarea acestor situa&#539;ii.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">O situa&#539;ie simpl&#259; este apelarea unei func&#539;ii care nu
            exist&#259;:</span></p>
    <p class="c0 c4"><span class="c1"></span></p><a id="t.dad960434ab3017fa495b4f291f8e9cfb5d5b60d"></a><a id="t.0"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c7">callSomeFunc();<br><br></span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Restul instruc&#539;iunilor&quot;</span><span
                        class="c7">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">Aici se apeleaz&#259; func&#539;ia callSomeFunc(), care nu este definit&#259;
            nic&#259;ieri. Prin urmare, la apelul acestei func&#539;ii, ne confrunt&#259;m cu o eroare.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c15"><span class="c20 c17">Uncaught ReferenceError: callSomeFunc is not defined</span></p>
    <p class="c0"><span class="c1">Toate celelalte instruc&#539;iuni care urmeaz&#259; dup&#259; linia unde apare
            eroarea nu sunt executate. Programul &icirc;&#537;i &icirc;ncheie execu&#539;ia.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">Situa&#539;ia poate p&#259;rea artificial&#259;, deoarece &#537;tim c&#259;
            func&#539;ia callSomeFunc nu este definit&#259;. Cu toate acestea, &icirc;ntr-o programare extins&#259;,
            unde diferi&#539;i dezvoltatori au definit diferite p&#259;r&#539;i ale programului, devine mai dificil
            s&#259; controlezi codul. Exist&#259; multe situa&#539;ii &icirc;n care unele erori pot fi anticipate
            &#537;i prevenite, iar altele nu.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c10">Pentru gestionarea acestor situa&#539;ii, JavaScript furnizeaz&#259;
            construc&#539;ia</span><span class="c17">&nbsp;try...catch...finally</span><span class="c1">, care are
            urm&#259;toarea defini&#539;ie formal&#259;:</span></p>
    <p class="c0 c4"><span class="c1"></span></p><a id="t.4c38677e9c9fa1cd2e65624cae3b9a069543023f"></a><a id="t.1"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp;</span><span
                        class="c10 c11">// instruc&#539;iuni blocului try</span><span class="c7"><br>}<br></span><span
                        class="c6">catch</span><span class="c7">&nbsp;(error) {<br> &nbsp;</span><span
                        class="c10 c11">// instruc&#539;iuni blocului catch</span><span class="c7"><br>}<br></span><span
                        class="c6">finally</span><span class="c7">&nbsp;{<br> &nbsp;</span><span class="c10 c11">//
                        instruc&#539;iuni blocului finally</span><span class="c7"><br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c10">Dup&#259; operatorul </span><span class="c17">try</span><span class="c1">, se
            define&#537;te un bloc de cod. &Icirc;n acest bloc sunt plasate instruc&#539;iunile pentru care poate
            ap&#259;rea o eroare poten&#539;ial&#259; &icirc;n timpul execu&#539;iei.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c10">Urm&#259;torul este operatorul </span><span class="c17">catch</span><span
            class="c1">. Dup&#259; acest operator, &icirc;n paranteze rotunde, se specific&#259; numele obiectului care
            va con&#539;ine informa&#539;ii despre eroare. Apoi urmeaz&#259; blocul catch. Acest bloc este executat doar
            &icirc;n cazul apari&#539;iei unei erori &icirc;n blocul try.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c10">Dup&#259; blocul catch, urmeaz&#259; operatorul </span><span
            class="c17">finally</span><span class="c1">, cu propriul s&#259;u bloc de instruc&#539;iuni. Acest bloc este
            executat la sf&acirc;r&#537;itul blocurilor try &#537;i catch, indiferent dac&#259; a ap&#259;rut o eroare
            sau nu.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">Este de remarcat faptul c&#259; doar blocul try este obligatoriu. Unul dintre
            celelalte blocuri - catch sau finally - poate fi omis. Cu toate acestea, unul dintre aceste blocuri (fie
            catch, fie finally) trebuie s&#259; fie prezent. Cu alte cuvinte, putem utiliza urm&#259;toarele variante
            ale acestei construc&#539;ii:</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c13">try...catch</span></p>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c13">try...finally</span></p>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c13">try...catch...finally</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">De exemplu, s&#259; gestion&#259;m situa&#539;ia anterioar&#259; cu func&#539;ia care
            nu exist&#259; folosind aceast&#259; construc&#539;ie:</span></p>
    <p class="c0 c4"><span class="c1"></span></p><a id="t.4520b7904467c1dfce287f4fe8acadd928cf3b7e"></a><a id="t.2"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;callSomeFunc();<br>
                        &nbsp; &nbsp;</span><span class="c8">console</span><span class="c7">.log(</span><span
                        class="c2">&quot;Sf&acirc;r&#537;itul blocului try&quot;</span><span
                        class="c7">);<br>}<br></span><span class="c6">catch</span><span class="c7">&nbsp;{<br> &nbsp;
                        &nbsp;</span><span class="c8">console</span><span class="c7">.log(</span><span
                        class="c2">&quot;A ap&#259;rut o eroare!&quot;</span><span class="c7">);<br>}<br></span><span
                        class="c8">console</span><span class="c7">.log(</span><span class="c2">&quot;Celelalte
                        instruc&#539;iuni&quot;</span><span class="c7">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c10">Astfel, mai &icirc;nt&acirc;i se execut&#259; blocul </span><span
            class="c17">try</span><span class="c10">. Cu toate acestea, &icirc;n timpul execut&#259;rii primei
            instruc&#539;iuni - apelul func&#539;iei callSomeFunc() - apare o eroare. Acest lucru duce la faptul c&#259;
            toate instruc&#539;iunile ulterioare din blocul try NU vor fi executate. Controlul se mut&#259; la blocul
        </span><span class="c17">catch</span><span class="c1">. &Icirc;n acest bloc se afi&#537;eaz&#259; un mesaj
            c&#259; a ap&#259;rut o eroare. Dup&#259; executarea blocului catch, sunt efectuate celelalte
            instruc&#539;iuni ale programului. Astfel, programul nu &icirc;&#537;i &icirc;ntrerupe execu&#539;ia
            &icirc;n caz de eroare &#537;i &icirc;&#537;i continu&#259; activitatea. </span></p>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c13">A ap&#259;rut o eroare!</span></p>
    <p class="c0"><span class="c13">Alte instruc&#539;iuni</span></p>
    <p class="c0 c4"><span class="c13"></span></p>
    <p class="c0"><span class="c1">S&#259; lu&#259;m &icirc;n considerare un alt exemplu:</span></p>
    <p class="c0 c4"><span class="c1"></span></p><a id="t.9787a33e903db148248b5fd25d947d5d3c260a37"></a><a id="t.3"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">function</span><span class="c7">&nbsp;</span><span
                        class="c8">callSomeFunc</span><span class="c7">() { </span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Func&#539;ia callSomeFunc&quot;</span><span
                        class="c7">); }<br><br></span><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp;
                        &nbsp;callSomeFunc();<br> &nbsp; &nbsp;</span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Sf&acirc;r&#537;itul blocului
                        try&quot;</span><span class="c7">);<br>} </span><span class="c6">catch</span><span
                        class="c7">&nbsp;(error) {<br> &nbsp; &nbsp;</span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;A ap&#259;rut o eroare!&quot;</span><span
                        class="c7">);<br>}<br><br></span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Alte instruc&#539;iuni&quot;</span><span
                        class="c7">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">Acum func&#539;ia callSomeFunc() este definit&#259; &icirc;n program, astfel
            &icirc;nc&acirc;t la apelarea func&#539;iei nu va ap&#259;rea nicio eroare, iar blocul try va continua
            s&#259; se execute p&acirc;n&#259; la sf&acirc;r&#537;it. &Icirc;n absen&#539;a unei erori, blocul catch nu
            va fi executat. Output-ul &icirc;n consol&#259; va fi urm&#259;torul:</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c13">Func&#539;ia callSomeFunc</span></p>
    <p class="c0"><span class="c13">Sf&acirc;r&#537;itul blocului try</span></p>
    <p class="c0"><span class="c13">Alte instruc&#539;iuni</span></p>
    <p class="c0 c4"><span class="c16"></span></p>
    <p class="c0"><span class="c16">Ob&#539;inerea unei erori &icirc;n blocul catch.</span></p>
    <p class="c0 c4"><span class="c1"></span></p>
    <p class="c0"><span class="c1">&Icirc;n calitate de parametru pentru blocul catch, este furnizat un obiect cu
            informa&#539;ii despre eroare.</span></p>
    <p class="c0 c4"><span class="c1"></span></p><a id="t.a77058ed23005ee845f753d7dd779fa90d86aac3"></a><a id="t.4"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;callSomeFunc();<br>
                        &nbsp; &nbsp;</span><span class="c8">console</span><span class="c7">.log(</span><span
                        class="c2">&quot;Sf&acirc;r&#537;itul blocului try&quot;</span><span class="c7">);<br>}
                    </span><span class="c6">catch</span><span class="c7">&nbsp;(eroare) {<br> &nbsp; &nbsp;</span><span
                        class="c8">console</span><span class="c7">.log(</span><span class="c2">&quot;A ap&#259;rut o
                        eroare!&quot;</span><span class="c7">);<br> &nbsp; &nbsp;</span><span
                        class="c8">console</span><span class="c7">.log(eroare);<br>}</span></p>
            </td>
        </tr>
    </table>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c1">&Icirc;n acest caz, vom ob&#539;ine un output &icirc;n consol&#259; similar cu
            urm&#259;torul:</span></p>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c13">A ap&#259;rut o eroare!</span></p>
    <p class="c5"><span class="c13">ReferenceError: callSomeFunc is not defined</span></p>
    <p class="c5"><span class="c13">&nbsp; &nbsp; at index.html:35</span></p>
    <p class="c5 c4"><span class="c13"></span></p>
    <p class="c5"><span class="c16">Bloc finally.</span></p>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c10">Construc&#539;ia try poate include &#537;i un bloc </span><span
            class="c17">finally</span><span class="c1">. Acest bloc poate fi utilizat &icirc;mpreun&#259; cu blocul
            catch sau &icirc;n locul acestuia. Blocul finally se execut&#259; indiferent dac&#259; apare o eroare sau
            nu. De exemplu:</span></p>
    <p class="c5 c4"><span class="c1"></span></p><a id="t.2919177e6de51ea913b5359bf6679a33e0089f84"></a><a id="t.5"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;callSomeFunc();<br>
                        &nbsp; &nbsp;</span><span class="c8">console</span><span class="c7">.log(</span><span
                        class="c2">&quot;Sf&acirc;r&#537;itul blocului try&quot;</span><span class="c7">);<br>}
                    </span><span class="c6">catch</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;</span><span
                        class="c8">console</span><span class="c7">.log(</span><span class="c2">&quot;A ap&#259;rut o
                        eroare&quot;</span><span class="c7">);<br>} </span><span class="c6">finally</span><span
                        class="c7">&nbsp;{<br> &nbsp; &nbsp;</span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Bloc finally&quot;</span><span
                        class="c7">);<br>}<br><br></span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Alte instruc&#539;iuni&quot;</span><span
                        class="c7">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c1">Output-ul &icirc;n consol&#259; al programului ar fi:</span></p>
    <p class="c5 c4"><span class="c1"></span></p><a id="t.b6256e40e9b0b0ab2d0694a09eb307e0efdea65f"></a><a id="t.6"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c7">A ap&#259;rut o eroare<br>Bloc </span><span
                        class="c6">finally</span><span class="c7"><br>Alte instruc&#539;iuni</span></p>
            </td>
        </tr>
    </table>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c1">Dac&#259; elimin&#259;m blocul catch &#537;i l&#259;s&#259;m doar blocul finally,
            eroarea nu va fi gestionat&#259;, iar programul se va &icirc;ncheia cu o eroare. Cu toate acestea, blocul
            finally va fi totu&#537;i executat:</span></p>
    <p class="c5 c4"><span class="c1"></span></p><a id="t.3c2e8b475a8d4b09de3b184904468d7914488639"></a><a id="t.7"></a>
    <table class="c3">
        <tr class="c9">
            <td class="c12" colspan="1" rowspan="1">
                <p class="c5"><span class="c6">try</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;callSomeFunc();<br>
                        &nbsp; &nbsp;</span><span class="c8">console</span><span class="c7">.log(</span><span
                        class="c2">&quot;Sf&acirc;r&#537;itul blocului try&quot;</span><span class="c7">);<br>}
                    </span><span class="c6">finally</span><span class="c7">&nbsp;{<br> &nbsp; &nbsp;</span><span
                        class="c8">console</span><span class="c7">.log(</span><span class="c2">&quot;Bloc
                        finally&quot;</span><span class="c7">);<br>}<br><br></span><span class="c8">console</span><span
                        class="c7">.log(</span><span class="c2">&quot;Alte instruc&#539;iuni&quot;</span><span
                        class="c7">);</span></p>
            </td>
        </tr>
    </table>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c1">Output-ul &icirc;n consol&#259; al programului ar fi:</span></p>
    <p class="c5 c4"><span class="c1"></span></p>
    <p class="c5"><span class="c17">Bloc finally</span></p>
    <p class="c18"><span class="c10 c20">Uncaught ReferenceError: callSomeFunc is not defined</span></p>
    <p class="c5 c4"><span class="c1"></span></p>
</body>

</html>